volumes:
  shared_data:

services:
  init-shared-data:
    image: alpine
    container_name: init-shared-data
    network_mode: host
    volumes:
      - shared_data:/data
    command: ["sh", "-c", "touch /data/log.txt && chmod 666 /data/log.txt"]
    restart: "no"

  go-gin:
    build:
      context: ./services/go-gin
      dockerfile: Dockerfile
    container_name: go-gin
    network_mode: host
    environment:
      - GIN_MODE=release
    volumes:
      - shared_data:/data
    depends_on:
      init-shared-data:
        condition: service_completed_successfully
    cpus: 0.3
    mem_limit: 128m
    mem_reservation: 64m
    restart: unless-stopped

  rust-actix:
    build:
      context: ./services/rust-actix
      dockerfile: Dockerfile
    container_name: rust-actix
    network_mode: host
    volumes:
      - shared_data:/data
    depends_on:
      init-shared-data:
        condition: service_completed_successfully
    cpus: 0.3
    mem_limit: 64m
    mem_reservation: 64m
    restart: unless-stopped

  python-fastapi:
    build:
      context: ./services/python-fastapi
      dockerfile: Dockerfile
    container_name: python-fastapi
    network_mode: host
    depends_on:
      init-shared-data:
        condition: service_completed_successfully
    cpus: 0.5
    mem_limit: 256m
    mem_reservation: 64m
    restart: unless-stopped
